//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndTravelSearchEngine.SF_service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SF_service.SF_serviceSoap")]
    public interface SF_serviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Search_Full", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.SearchResultFlights DELETE_Search_Full(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, string is_rambler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Search_Full_JSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.SearchResultFlightsJson DELETE_Search_Full_JSON(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, decimal course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Search_First_JSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.SearchResultJson DELETE_Search_First_JSON(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, decimal course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search_First", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.SearchResultFlights Search_First(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, string my_search_id, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InitSearch(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetCurrentState(string requestId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.SearchResult GetCurrentResults(string requestId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentResultsFlights", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.SearchResultFlights GetCurrentResultsFlights(string requestId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentResultsJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.SearchResultJson GetCurrentResultsJson(string requestId, decimal course, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WaitSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int WaitSearch(string requestId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightRulesByTicketId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.FlightRules GetFlightRulesByTicketId(long ticket_id, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Flight_Details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.FlightDetails[] Flight_Details(string flightToken, string searchId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.Flight GetFlightInfo(string flightToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.Flight GetFlight(string flightToken, string searchId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTicketId(string searchId, string flightToken, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookFlight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.BookingResult BookFlight(string flightToken, ClickAndTravelSearchEngine.SF_service.Customer customer, ClickAndTravelSearchEngine.SF_service.Passenger[] passengers, System.DateTime tour_end_date, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckFlights", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.PriceLink[] CheckFlights(string[] hashes, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.TicketInfo GetTicketInfo(string bookId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BuyTicket(string bookId, string secure_sign, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClickAndTravelSearchEngine.SF_service.FileContainer[] LoadTickets(string bookId, string PartnerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Clearing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Clearing();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Route : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RouteSegment[] segmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public RouteSegment[] Segments {
            get {
                return this.segmentsField;
            }
            set {
                this.segmentsField = value;
                this.RaisePropertyChanged("Segments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RouteSegment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private string locationBeginField;
        
        private string locationEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LocationBegin {
            get {
                return this.locationBeginField;
            }
            set {
                this.locationBeginField = value;
                this.RaisePropertyChanged("LocationBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LocationEnd {
            get {
                return this.locationEndField;
            }
            set {
                this.locationEndField = value;
                this.RaisePropertyChanged("LocationEnd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileTitleField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileTitle {
            get {
                return this.fileTitleField;
            }
            set {
                this.fileTitleField = value;
                this.RaisePropertyChanged("FileTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
                this.RaisePropertyChanged("FilePath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TicketInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal rubPriceField;
        
        private string mainTuristField;
        
        private int turistCountField;
        
        private string routeFromField;
        
        private string routeToField;
        
        private bool isBookingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal RubPrice {
            get {
                return this.rubPriceField;
            }
            set {
                this.rubPriceField = value;
                this.RaisePropertyChanged("RubPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MainTurist {
            get {
                return this.mainTuristField;
            }
            set {
                this.mainTuristField = value;
                this.RaisePropertyChanged("MainTurist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TuristCount {
            get {
                return this.turistCountField;
            }
            set {
                this.turistCountField = value;
                this.RaisePropertyChanged("TuristCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RouteFrom {
            get {
                return this.routeFromField;
            }
            set {
                this.routeFromField = value;
                this.RaisePropertyChanged("RouteFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RouteTo {
            get {
                return this.routeToField;
            }
            set {
                this.routeToField = value;
                this.RaisePropertyChanged("RouteTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsBooking {
            get {
                return this.isBookingField;
            }
            set {
                this.isBookingField = value;
                this.RaisePropertyChanged("IsBooking");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PriceLink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int priceField;
        
        private string linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("Link");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BookingResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private int timerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int timer {
            get {
                return this.timerField;
            }
            set {
                this.timerField = value;
                this.RaisePropertyChanged("timer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Passenger : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string fnameField;
        
        private string otcField;
        
        private string citizenField;
        
        private System.DateTime birthField;
        
        private string genderField;
        
        private string pasportField;
        
        private System.DateTime passportExpireDateField;
        
        private string frequentFlyerAirlineField;
        
        private string frequentFlyerNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
                this.RaisePropertyChanged("Fname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Otc {
            get {
                return this.otcField;
            }
            set {
                this.otcField = value;
                this.RaisePropertyChanged("Otc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Citizen {
            get {
                return this.citizenField;
            }
            set {
                this.citizenField = value;
                this.RaisePropertyChanged("Citizen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Birth {
            get {
                return this.birthField;
            }
            set {
                this.birthField = value;
                this.RaisePropertyChanged("Birth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Pasport {
            get {
                return this.pasportField;
            }
            set {
                this.pasportField = value;
                this.RaisePropertyChanged("Pasport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime PassportExpireDate {
            get {
                return this.passportExpireDateField;
            }
            set {
                this.passportExpireDateField = value;
                this.RaisePropertyChanged("PassportExpireDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FrequentFlyerAirline {
            get {
                return this.frequentFlyerAirlineField;
            }
            set {
                this.frequentFlyerAirlineField = value;
                this.RaisePropertyChanged("FrequentFlyerAirline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FrequentFlyerNumber {
            get {
                return this.frequentFlyerNumberField;
            }
            set {
                this.frequentFlyerNumberField = value;
                this.RaisePropertyChanged("FrequentFlyerNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string mailField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("Mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string numberField;
        
        private string titleField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightRules : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool allowedReturnBeforeField;
        
        private bool allowedReturnAfterField;
        
        private bool allowedChangesBeforeField;
        
        private bool allowedChangesAfterField;
        
        private string rulesTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AllowedReturnBefore {
            get {
                return this.allowedReturnBeforeField;
            }
            set {
                this.allowedReturnBeforeField = value;
                this.RaisePropertyChanged("AllowedReturnBefore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool AllowedReturnAfter {
            get {
                return this.allowedReturnAfterField;
            }
            set {
                this.allowedReturnAfterField = value;
                this.RaisePropertyChanged("AllowedReturnAfter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool AllowedChangesBefore {
            get {
                return this.allowedChangesBeforeField;
            }
            set {
                this.allowedChangesBeforeField = value;
                this.RaisePropertyChanged("AllowedChangesBefore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool AllowedChangesAfter {
            get {
                return this.allowedChangesAfterField;
            }
            set {
                this.allowedChangesAfterField = value;
                this.RaisePropertyChanged("AllowedChangesAfter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RulesText {
            get {
                return this.rulesTextField;
            }
            set {
                this.rulesTextField = value;
                this.RaisePropertyChanged("RulesText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Variant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flightTimeField;
        
        private string idField;
        
        private Leg[] legsField;
        
        private string keyField;
        
        private int startTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FlightTime {
            get {
                return this.flightTimeField;
            }
            set {
                this.flightTimeField = value;
                this.RaisePropertyChanged("FlightTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Leg[] Legs {
            get {
                return this.legsField;
            }
            set {
                this.legsField = value;
                this.RaisePropertyChanged("Legs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Leg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceClassField;
        
        private string bookingClassField;
        
        private string airlineField;
        
        private string flightNumberField;
        
        private string airportBeginNameField;
        
        private string airportEndNameField;
        
        private string locationBeginNameField;
        
        private string locationBeginField;
        
        private string locationEndNameField;
        
        private string locationEndField;
        
        private System.DateTime dateBeginField;
        
        private System.DateTime dateEndField;
        
        private string boardField;
        
        private string boardNameField;
        
        private string remarksSearchContextField;
        
        private int durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceClass {
            get {
                return this.serviceClassField;
            }
            set {
                this.serviceClassField = value;
                this.RaisePropertyChanged("ServiceClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BookingClass {
            get {
                return this.bookingClassField;
            }
            set {
                this.bookingClassField = value;
                this.RaisePropertyChanged("BookingClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
                this.RaisePropertyChanged("Airline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FlightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
                this.RaisePropertyChanged("FlightNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AirportBeginName {
            get {
                return this.airportBeginNameField;
            }
            set {
                this.airportBeginNameField = value;
                this.RaisePropertyChanged("AirportBeginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AirportEndName {
            get {
                return this.airportEndNameField;
            }
            set {
                this.airportEndNameField = value;
                this.RaisePropertyChanged("AirportEndName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LocationBeginName {
            get {
                return this.locationBeginNameField;
            }
            set {
                this.locationBeginNameField = value;
                this.RaisePropertyChanged("LocationBeginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LocationBegin {
            get {
                return this.locationBeginField;
            }
            set {
                this.locationBeginField = value;
                this.RaisePropertyChanged("LocationBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LocationEndName {
            get {
                return this.locationEndNameField;
            }
            set {
                this.locationEndNameField = value;
                this.RaisePropertyChanged("LocationEndName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LocationEnd {
            get {
                return this.locationEndField;
            }
            set {
                this.locationEndField = value;
                this.RaisePropertyChanged("LocationEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime DateBegin {
            get {
                return this.dateBeginField;
            }
            set {
                this.dateBeginField = value;
                this.RaisePropertyChanged("DateBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime DateEnd {
            get {
                return this.dateEndField;
            }
            set {
                this.dateEndField = value;
                this.RaisePropertyChanged("DateEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Board {
            get {
                return this.boardField;
            }
            set {
                this.boardField = value;
                this.RaisePropertyChanged("Board");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BoardName {
            get {
                return this.boardNameField;
            }
            set {
                this.boardNameField = value;
                this.RaisePropertyChanged("BoardName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RemarksSearchContext {
            get {
                return this.remarksSearchContextField;
            }
            set {
                this.remarksSearchContextField = value;
                this.RaisePropertyChanged("RemarksSearchContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Direction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Variant[] variantsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Variant[] Variants {
            get {
                return this.variantsField;
            }
            set {
                this.variantsField = value;
                this.RaisePropertyChanged("Variants");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Fare : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineField;
        
        private string airlineCodeField;
        
        private int priceField;
        
        private string idField;
        
        private Direction[] directionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
                this.RaisePropertyChanged("Airline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AirlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
                this.RaisePropertyChanged("AirlineCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Direction[] Directions {
            get {
                return this.directionsField;
            }
            set {
                this.directionsField = value;
                this.RaisePropertyChanged("Directions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int isFinishedField;
        
        private string searchIdField;
        
        private Fare[] faresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IsFinished {
            get {
                return this.isFinishedField;
            }
            set {
                this.isFinishedField = value;
                this.RaisePropertyChanged("IsFinished");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchId {
            get {
                return this.searchIdField;
            }
            set {
                this.searchIdField = value;
                this.RaisePropertyChanged("SearchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Fare[] Fares {
            get {
                return this.faresField;
            }
            set {
                this.faresField = value;
                this.RaisePropertyChanged("Fares");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResultJson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string changesField;
        
        private string airportsField;
        
        private string faresField;
        
        private string airlinesField;
        
        private string searchIdField;
        
        private int isFinishedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Changes {
            get {
                return this.changesField;
            }
            set {
                this.changesField = value;
                this.RaisePropertyChanged("Changes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Airports {
            get {
                return this.airportsField;
            }
            set {
                this.airportsField = value;
                this.RaisePropertyChanged("Airports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Fares {
            get {
                return this.faresField;
            }
            set {
                this.faresField = value;
                this.RaisePropertyChanged("Fares");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Airlines {
            get {
                return this.airlinesField;
            }
            set {
                this.airlinesField = value;
                this.RaisePropertyChanged("Airlines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SearchId {
            get {
                return this.searchIdField;
            }
            set {
                this.searchIdField = value;
                this.RaisePropertyChanged("SearchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int IsFinished {
            get {
                return this.isFinishedField;
            }
            set {
                this.isFinishedField = value;
                this.RaisePropertyChanged("IsFinished");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResultFlightsJson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flightsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
                this.RaisePropertyChanged("Flights");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int flightLongField;
        
        private Leg[] legsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FlightLong {
            get {
                return this.flightLongField;
            }
            set {
                this.flightLongField = value;
                this.RaisePropertyChanged("FlightLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Leg[] Legs {
            get {
                return this.legsField;
            }
            set {
                this.legsField = value;
                this.RaisePropertyChanged("Legs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Flight : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string fullIdField;
        
        private int priceField;
        
        private string airlineField;
        
        private string airlineCodeField;
        
        private string keyField;
        
        private string timeLimitField;
        
        private FlightPart[] partsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullId {
            get {
                return this.fullIdField;
            }
            set {
                this.fullIdField = value;
                this.RaisePropertyChanged("FullId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
                this.RaisePropertyChanged("Airline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AirlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
                this.RaisePropertyChanged("AirlineCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TimeLimit {
            get {
                return this.timeLimitField;
            }
            set {
                this.timeLimitField = value;
                this.RaisePropertyChanged("TimeLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public FlightPart[] Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResultFlights : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int isFinishedField;
        
        private string requestIdField;
        
        private Flight[] flightsField;
        
        private int searchIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IsFinished {
            get {
                return this.isFinishedField;
            }
            set {
                this.isFinishedField = value;
                this.RaisePropertyChanged("IsFinished");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Flight[] Flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
                this.RaisePropertyChanged("Flights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SearchId {
            get {
                return this.searchIdField;
            }
            set {
                this.searchIdField = value;
                this.RaisePropertyChanged("SearchId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SF_serviceSoapChannel : ClickAndTravelSearchEngine.SF_service.SF_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SF_serviceSoapClient : System.ServiceModel.ClientBase<ClickAndTravelSearchEngine.SF_service.SF_serviceSoap>, ClickAndTravelSearchEngine.SF_service.SF_serviceSoap {
        
        public SF_serviceSoapClient() {
        }
        
        public SF_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SF_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SF_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SF_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClickAndTravelSearchEngine.SF_service.SearchResultFlights DELETE_Search_Full(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, string is_rambler) {
            return base.Channel.DELETE_Search_Full(route, adult, children, inf, serviceClass, is_rambler);
        }
        
        public ClickAndTravelSearchEngine.SF_service.SearchResultFlightsJson DELETE_Search_Full_JSON(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, decimal course) {
            return base.Channel.DELETE_Search_Full_JSON(route, adult, children, inf, serviceClass, course);
        }
        
        public ClickAndTravelSearchEngine.SF_service.SearchResultJson DELETE_Search_First_JSON(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, decimal course) {
            return base.Channel.DELETE_Search_First_JSON(route, adult, children, inf, serviceClass, course);
        }
        
        public ClickAndTravelSearchEngine.SF_service.SearchResultFlights Search_First(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, string my_search_id, string PartnerCode) {
            return base.Channel.Search_First(route, adult, children, inf, serviceClass, my_search_id, PartnerCode);
        }
        
        public string InitSearch(ClickAndTravelSearchEngine.SF_service.Route route, int adult, int children, int inf, string serviceClass, string PartnerCode) {
            return base.Channel.InitSearch(route, adult, children, inf, serviceClass, PartnerCode);
        }
        
        public int GetCurrentState(string requestId, string PartnerCode) {
            return base.Channel.GetCurrentState(requestId, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.SearchResult GetCurrentResults(string requestId, string PartnerCode) {
            return base.Channel.GetCurrentResults(requestId, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.SearchResultFlights GetCurrentResultsFlights(string requestId, string PartnerCode) {
            return base.Channel.GetCurrentResultsFlights(requestId, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.SearchResultJson GetCurrentResultsJson(string requestId, decimal course, string PartnerCode) {
            return base.Channel.GetCurrentResultsJson(requestId, course, PartnerCode);
        }
        
        public int WaitSearch(string requestId, string PartnerCode) {
            return base.Channel.WaitSearch(requestId, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.FlightRules GetFlightRulesByTicketId(long ticket_id, string PartnerCode) {
            return base.Channel.GetFlightRulesByTicketId(ticket_id, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.FlightDetails[] Flight_Details(string flightToken, string searchId, string PartnerCode) {
            return base.Channel.Flight_Details(flightToken, searchId, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.Flight GetFlightInfo(string flightToken) {
            return base.Channel.GetFlightInfo(flightToken);
        }
        
        public ClickAndTravelSearchEngine.SF_service.Flight GetFlight(string flightToken, string searchId, string PartnerCode) {
            return base.Channel.GetFlight(flightToken, searchId, PartnerCode);
        }
        
        public string GetTicketId(string searchId, string flightToken, string PartnerCode) {
            return base.Channel.GetTicketId(searchId, flightToken, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.BookingResult BookFlight(string flightToken, ClickAndTravelSearchEngine.SF_service.Customer customer, ClickAndTravelSearchEngine.SF_service.Passenger[] passengers, System.DateTime tour_end_date, string PartnerCode) {
            return base.Channel.BookFlight(flightToken, customer, passengers, tour_end_date, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.PriceLink[] CheckFlights(string[] hashes, string PartnerCode) {
            return base.Channel.CheckFlights(hashes, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.TicketInfo GetTicketInfo(string bookId, string PartnerCode) {
            return base.Channel.GetTicketInfo(bookId, PartnerCode);
        }
        
        public string BuyTicket(string bookId, string secure_sign, string PartnerCode) {
            return base.Channel.BuyTicket(bookId, secure_sign, PartnerCode);
        }
        
        public ClickAndTravelSearchEngine.SF_service.FileContainer[] LoadTickets(string bookId, string PartnerCode) {
            return base.Channel.LoadTickets(bookId, PartnerCode);
        }
        
        public void Clearing() {
            base.Channel.Clearing();
        }
    }
}
